# Generated by Django 4.2 on 2023-05-05 10:00

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_staff_alter_account_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.file_path),
        ),
    ]
