# Generated by Django 4.2 on 2023-05-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contact_subscribe_delete_type_and_more'),
        ('account', '0004_alter_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
    ]
