# Generated by Django 4.2 on 2023-05-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_time_shift_job_types'),
        ('main', '0002_category_tag_timeshift'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeShift',
            new_name='Type',
        ),
    ]
