# Generated by Django 4.2 on 2023-05-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_remove_job_types_remove_job_working_day'),
        ('main', '0003_rename_timeshift_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(max_length=218)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='location',
        ),
    ]
