# Generated by Django 4.2 on 2023-05-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='price',
            new_name='salary',
        ),
    ]
