# Generated by Django 4.2 on 2023-05-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='time_shift',
            new_name='types',
        ),
    ]
