# Generated by Django 4.2 on 2023-05-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_time_shift_job_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='author',
        ),
    ]
