# Generated by Django 4.2 on 2023-05-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_rename_user_like_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='created_date',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
